---
forwarder_config_path: /etc/fluent/fluentd.conf

forwarder_sources:
  - tag: "system.syslog"
    type: tail
    path: /var/log/syslog
    pos_file: /var/log/fluentd/syslog.pos
    parse_type: syslog

forwarder_aggregator_host: localhost
forwarder_aggregator_port: 24224
forwarder_heartbeat_type: tcp

forwarder_buffer_type: file
forwarder_buffer_path: /var/log/fluentd/buffer
forwarder_flush_interval: 5s
forwarder_retry_max_times: 10

forwarder_service_name: fluentd
