---
fluentd_package_name: fluent-package
fluentd_version: ""
fluentd_manage_repo: true

fluentd_service_name: fluentd
fluentd_service_enabled: true
fluentd_service_state: started

fluentd_config_path: /etc/fluent/fluentd.conf
fluentd_config_template: fluentd.conf.j2
fluentd_user: _fluentd
fluentd_group: _fluentd

fluentd_plugins: []
# - name: fluent-plugin-elasticsearch
#   version: "5.4.3"

fluentd_log_level: info
fluentd_suppress_repeated_stacktrace: true
fluentd_workers: 1
