---
install_package_name: fluent-package
install_version: ""
install_manage_repo: true

install_service_name: fluentd
install_service_enabled: true
install_service_state: started

install_config_path: /etc/fluent/fluentd.conf
install_config_template: fluentd.conf.j2
install_user: _fluentd
install_group: _fluentd

install_plugins: []
# - name: fluent-plugin-elasticsearch
#   version: "5.4.3"

install_log_level: info
install_suppress_repeated_stacktrace: true
install_workers: 1
