---
install__repo_url: "https://packages.treasuredata.com/lts/5/{{ ansible_distribution | lower }}/{{ ansible_distribution_release }}/"
install__gpg_key: "https://packages.treasuredata.com/GPG-KEY-td-agent"
install__repo_file: "/etc/apt/sources.list.d/fluent-package.list"
